/**
 * Server-only loader for the US-states GeoJSON FeatureCollection.
 *
 * Reads `public/data/us-states.json` from disk on first call and
 * caches the parsed object across requests. The file is generated by
 * `npm run fetch:map-data` (see scripts/fetch_map_data.py) and checked
 * into the repo, so production builds don't need network access.
 *
 * Coordinates are raw lat/lon (NAD83/EPSG:4269; ≤ 1m off WGS84 in
 * CONUS, indistinguishable at our zoom). The renderer applies the
 * appropriate projection per context — Albers USA composite for the
 * national overview, a state-fitted Albers Equal-Area Conic for each
 * state detail view. See lib/state-projection.ts.
 */
import "server-only";

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { Feature, FeatureCollection, Geometry } from "geojson";

/** Properties present on each state feature in our pipeline. */
export interface StateFeatureProperties {
  /** Full state name, e.g. "California". */
  name: string;
  /** 2-character postal abbreviation, e.g. "CA". */
  abbr: string;
}

export type StatesGeoJSON = FeatureCollection<Geometry, StateFeatureProperties>;
export type StateFeature = Feature<Geometry, StateFeatureProperties>;

let cached: StatesGeoJSON | null = null;

export async function loadStatesGeoJSON(): Promise<StatesGeoJSON> {
  if (cached) return cached;
  const path = join(process.cwd(), "public", "data", "us-states.json");
  const buf = await readFile(path, "utf-8");
  const parsed = JSON.parse(buf) as StatesGeoJSON;
  cached = parsed;
  return parsed;
}
